[package]
name = "xniffer-cli"
version = "0.1.0"
edition = "2021"
description = "A simple exif sniffer using metaxata"
authors = ["3top1a <3top1a.official@gmail.com>"]

[dependencies]
rayon = "1.5"
metaxata = {path = "../metaxata/"}
comfy-table = "5.0"
termsize = "0.1"
hex = "0.4"
clap = "3.1"
